name: catalog-api

on:
#--------------------- Above exists in the yml already
 workflow_dispatch:
  # Inputs the workflow accepts.
  inputs:
   name:
     # Friendly description to be shown in the UI instead of 'name'
     description: 'exec name'
     # Default value if no value is explicitly provided
     default: 'default execution'
     # Input has to be provided for the workflow to run
     required: false
 #--------------------- below exists in the yml already
  push:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
  
  pull_request:
    branches:
    - dev
    
    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
env:
  SERVICE: catalog-api
  IMAGE: catalog.api
  DOTNET_VERSION: 6.0.x
  PROJECT_PATH: Services/Catalog/Catalog.API
  TESTS_PATH: Services/Catalog/Catalog.UnitTests

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build-test
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        dotnet_version: ${{ env.DOTNET_VERSION }}
        project_path: ${{ env.PROJECT_PATH }}
        tests_path: ${{ env.TESTS_PATH }}

  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ secrets.REGISTRY_HOST }}
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.USERNAME }}
        registry_password: ${{ secrets.PASSWORD }}

#---------------------------------------------------------------
    - name: Compose test ${{ env.SERVICE }}
      run: sudo -E docker-compose -f ./docker-compose-tests.yml -f ./docker-compose-tests.override.yml up ${{ env.SERVICE }}-functional-test ${{ env.SERVICE }}-unit-test
      working-directory: ./src
      shell: bash
      env:
        TAG: ${{ env.BRANCH }}
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
    
    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: src/tests-results/*.xml

    - uses: dorny/test-reporter@v1
      with:          
        name: .NET Tests                  # Name of the check run which will be created
        path: src/tests-results/*.xml     # Path to test results
        reporter: dotnet-trx              # Format of test results